
INSERT INTO PRICE (VEHICLE_ID , CURRENCY , PRICE ) VALUES ( 1,'e',8000); 
INSERT INTO PRICE (VEHICLE_ID , CURRENCY , PRICE ) VALUES ( 2,'$',5000); 
INSERT INTO PRICE (VEHICLE_ID , CURRENCY , PRICE ) VALUES ( 3,'e',6000); 